set nocompatible
filetype off

set rtp+=~/.vim/bundle/Vundle.vim
call vundle#begin()

Plugin 'VundleVim/Vundle.vim'

Plugin 'preservim/nerdtree'
Plugin 'vim-airline/vim-airline'
Plugin 'christoomey/vim-tmux-navigator'

call vundle#end()

filetype plugin indent on
syntax on

" indentation
set tabstop=4
set softtabstop=4
set shiftwidth=4
set expandtab
set autoindent
set smartindent

" line numbers
set number
set numberwidth=5

" right margin
set colorcolumn=81

" nerdtree
nnoremap <leader>n :NERDTreeToggle<CR>

" split switch
nnoremap <C-h> <C-w>h
nnoremap <C-j> <C-w>j
nnoremap <C-k> <C-w>k
nnoremap <C-l> <C-w>l
